fix package requirements for windows
#1019 no longer addresses issue of textfsm import in windows because of a change in ntc-templates==1.4.2  :

ImportError: cannot import name 'clitable' from 'textfsm' (<redacted>\lib\site-packages\textfsm\__init__.py)